<a href="https://colab.research.google.com/github/Ray88888888/QI-PS/blob/main/APT_PS2_(Ray%2C_GGV%2C_Coco%2C_Faye).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install --upgrade xlrd
!pip install --upgrade pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (1.1.0)
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 2.3 MB/s
Installing collected packages: xlrd
  Attempting uninstall: xlrd
    Found existing installation: xlrd 1.1.0
    Uninstalling xlrd-1.1.0:
      Successfully uninstalled xlrd-1.1.0
Successfully installed xlrd-2.0.1
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.2.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [6]:
!pip install pingouin

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pingouin
  Downloading pingouin-0.5.2.tar.gz (185 kB)
     |████████████████████████████████| 185 kB 5.6 MB/s
Requirement already satisfied: numpy>=1.19 in /usr/local/lib/python3.7/dist-packages (from pingouin) (1.21.6)
Requirement already satisfied: scipy>=1.7 in /usr/local/lib/python3.7/dist-packages (from pingouin) (1.7.3)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.7/dist-packages (from pingouin) (1.3.5)
Requirement already satisfied: matplotlib>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from pingouin) (3.2.2)
Requirement already satisfied: seaborn>=0.11 in /usr/local/lib/python3.7/dist-packages (from pingouin) (0.11.2)
Collecting statsmodels>=0.13
  Downloading statsmodels-0.13.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.8 MB)
     |████████████████████████████████| 9.8 MB 61.0 MB/s
Requirement already satisfied: scikit-learn<1.1.0 in /usr/local/lib/python3.7/dist-packages (from pingouin) (1.0.2)
Collecting pandas_flavor>=0.2.0
  Downloading pandas_flavor-0.3.0-py3-none-any.whl (6.3 kB)
Collecting outdated
  Downloading outdated-0.2.1-py3-none-any.whl (7.5 kB)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from pingouin) (0.8.10)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.2->pingouin) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.2->pingouin) (1.4.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.2->pingouin) (3.0.9)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.2->pingouin) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=3.0.2->pingouin) (4.1.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0->pingouin) (2022.2.1)
Requirement already satisfied: xarray in /usr/local/lib/python3.7/dist-packages (from pandas_flavor>=0.2.0->pingouin) (0.20.2)
Collecting pandas_flavor>=0.2.0
  Downloading pandas_flavor-0.2.0-py2.py3-none-any.whl (6.6 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=3.0.2->pingouin) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<1.1.0->pingouin) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<1.1.0->pingouin) (3.1.0)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.7/dist-packages (from statsmodels>=0.13->pingouin) (0.5.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.7/dist-packages (from statsmodels>=0.13->pingouin) (21.3)
Collecting littleutils
  Downloading littleutils-0.2.2.tar.gz (6.6 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from outdated->pingouin) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->outdated->pingouin) (2022.6.15)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->outdated->pingouin) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->outdated->pingouin) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->outdated->pingouin) (1.24.3)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from xarray->pandas_flavor>=0.2.0->pingouin) (4.12.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->xarray->pandas_flavor>=0.2.0->pingouin) (3.8.1)
Building wheels for collected packages: pingouin, littleutils
  Building wheel for pingouin (setup.py) ... done
  Created wheel for pingouin: filename=pingouin-0.5.2-py3-none-any.whl size=196206 sha256=3bf0e75df95fd9324a882d03a201b6bb691e9c3f957660aaefc9da10b16ad0e9
  Stored in directory: /root/.cache/pip/wheels/11/5a/63/a6d32fc26fa462c731f65480bfb98ff7bd39b8ebcb4bc6c2fe
  Building wheel for littleutils (setup.py) ... done
  Created wheel for littleutils: filename=littleutils-0.2.2-py3-none-any.whl size=7048 sha256=15f50b5cba0bca81dd29be3ea88c33e41814562c373c237213492746b7b307ff
  Stored in directory: /root/.cache/pip/wheels/d6/64/cd/32819b511a488e4993f2fab909a95330289c3f4e0f6ef4676d
Successfully built pingouin littleutils
Installing collected packages: littleutils, statsmodels, pandas-flavor, outdated, pingouin
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.12.2
    Uninstalling statsmodels-0.12.2:
      Successfully uninstalled statsmodels-0.12.2
Successfully installed littleutils-0.2.2 outdated-0.2.1 pandas-flavor-0.2.0 pingouin-0.5.2 statsmodels-0.13.2

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
import datetime
import pingouin as pg

## Part I (Ray & Zhewei)

In [58]:
df25=pd.read_csv('https://raw.githubusercontent.com/Ray88888888/QI-PS/main/25_Portfolios_5x5.CSV', header=0,index_col=0)
df25.replace([-99.99,-999],[np.nan,np.nan],inplace=True)
df25 = df25[:202208]
df25

,1,2,3,4,5,6,7,8,9,10,...,20,21,22,23,24,25,Mkt-RF,SMB,HML,RF
193201,5.5527,-5.9907,8.3063,14.2165,6.0887,-0.3044,-1.3482,5.4795,14.3969,18.3762,...,1.9409,-3.6929,-1.5137,2.5942,10.9191,7.8947,-1.58,3.93,9.03,0.23
193202,-12.7896,-0.0154,5.8810,-1.9977,3.4665,-5.4119,3.2908,-2.3221,-4.5816,-1.1353,...,3.7601,7.2592,5.6243,3.3144,-3.3170,14.6341,5.46,-2.78,-1.46,0.23
193203,-23.0216,-3.9056,-3.2485,-11.5349,-11.8922,-4.8922,-14.1355,-11.4193,-4.3036,-13.2422,...,-10.1478,-10.9710,-10.4864,-13.7685,-23.2023,2.1277,-11.21,2.27,-2.32,0.16
193204,-40.7620,-16.8293,-25.8159,-19.4433,-18.0051,-19.9193,-8.1414,-14.4050,-17.4530,-14.3736,...,-15.2035,-18.1767,-20.7489,-18.7549,-22.1641,-22.9167,-17.96,1.45,1.43,0.11
193205,-12.8641,-35.2372,-5.8922,-5.1067,-10.2889,-11.9878,-21.7501,-22.0395,-17.3451,-20.4772,...,-27.9405,-20.4176,-16.9797,-31.1270,-36.7136,-10.8108,-20.51,3.91,-2.98,0.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202204,-16.1458,-13.2365,-9.9863,-6.3449,-4.0988,-18.1950,-12.0671,-8.5393,-6.2858,-5.9654,...,-7.0521,-10.8609,-9.2140,-7.1498,-5.5172,-7.4225,-9.46,-1.41,6.19,0.01
202205,-5.8265,-3.5601,-0.9777,-0.1506,2.9569,-3.2936,-2.8180,2.0090,4.0419,5.7494,...,8.2899,-3.0113,-0.3170,2.8100,6.4726,6.4003,-0.34,-1.85,8.41,0.03
202206,-6.6490,-4.2722,-4.2452,-6.5665,-9.8769,-2.0535,-6.2438,-6.7874,-6.2183,-12.9730,...,-13.2412,-7.8059,-5.5254,-8.7814,-12.0979,-12.1789,-8.43,2.09,-5.97,0.06
202207,15.3839,12.9453,8.2644,9.6279,5.7074,12.7958,13.6533,11.6312,9.9950,9.2214,...,6.1561,12.7225,5.5066,4.1833,7.3500,6.7965,9.57,2.81,-4.10,0.08
202208,3.8098,-0.1388,0.5269,-0.0219,-0.2621,3.6693,-0.8214,-4.4867,-3.8408,-2.4716,...,-0.3650,-5.3349,-3.1101,-1.9065,0.0550,-3.0467,-3.78,1.39,0.31,0.19

In [41]:
df25_mean = []
for i in range(25):
  df25_mean.append(df25[str(i+1)].mean())
df25_mean

[1.046660294117647,
 1.1914723345588234,
 1.4514845588235294,
 1.6023375919117646,
 1.7828433823529413,
 1.0592932904411765,
 1.3305533088235295,
 1.358875643382353,
 1.464778400735294,
 1.6511291360294118,
 1.1042128676470588,
 1.2658803308823527,
 1.2775501838235295,
 1.4076871323529412,
 1.5117045036764707,
 1.0770167279411764,
 1.143673713235294,
 1.244009099264706,
 1.339306525735294,
 1.439114338235294,
 0.9780632352941175,
 0.9497681985294117,
 1.094745036764706,
 1.0421558823529413,
 1.317874356617647]

In [43]:
'''Report mean returns'''
def present_in_5square(df25):
  df25_return = pd.DataFrame(index=['Small','2','3','4','Big'], columns=['Low','2','3','4','High'], dtype=float)
  for i in range(25):
    n = i//5
    m = i%5
    df25_return.iloc[n][m] = df25[i]
  return df25_return

present_in_5square(df25_mean)

            Low         2         3         4      High
Small  1.046660  1.191472  1.451485  1.602338  1.782843
2      1.059293  1.330553  1.358876  1.464778  1.651129
3      1.104213  1.265880  1.277550  1.407687  1.511705
4      1.077017  1.143674  1.244009  1.339307  1.439114
Big    0.978063  0.949768  1.094745  1.042156  1.317874

In [16]:
name_of_25_port =[]
for i in ['Small','2','3','4','Big']:
  for j in ['Low','2','3','4','High']:
    name_of_25_port.append(i+'_'+j)
name_of_25_port

['Small_Low',
 'Small_2',
 'Small_3',
 'Small_4',
 'Small_High',
 '2_Low',
 '2_2',
 '2_3',
 '2_4',
 '2_High',
 '3_Low',
 '3_2',
 '3_3',
 '3_4',
 '3_High',
 '4_Low',
 '4_2',
 '4_3',
 '4_4',
 '4_High',
 'Big_Low',
 'Big_2',
 'Big_3',
 'Big_4',
 'Big_High']

In [65]:
'''Run OLS time-series regressions to find parameter estimates of αˆ,βˆ,λˆ'''
'''test CAPM & Report standard errors'''
df_timeseries_est = pd.DataFrame(index=df25.columns[:-4], columns=['α','α_pvalue','β','β_pvalue','α_se','β_se'], dtype=float)
for i in df25.columns[:-4]:
  lm = pg.linear_regression(df25['Mkt-RF'],df25[i]-df25['RF'])
  df_timeseries_est['α'][i] = lm.coef[0]
  df_timeseries_est['α_pvalue'][i] = lm.pval[0]
  df_timeseries_est['β'][i] = lm.coef[1]
  df_timeseries_est['β_pvalue'][i] = lm.pval[1]
  df_timeseries_est['α_se'][i] = lm.se[0]
  df_timeseries_est['β_se'][i] = lm.se[1]
for i in df_timeseries_est.columns:
  print(i)
  print(present_in_5square(df_timeseries_est[i]).round(4))
  print('\n')

print('λ')
print(df25['Mkt-RF'].mean())
print('λ_se')
print(df25['Mkt-RF'].std()/(len(df25.index)**0.5))

α
          Low       2       3       4    High
Small -0.4334 -0.1410  0.1259  0.3942  0.4920
2     -0.1823  0.1260  0.1810  0.2826  0.3461
3     -0.1184  0.1571  0.1611  0.2552  0.2314
4      0.0022  0.0553  0.1495  0.2059  0.1226
Big    0.0033 -0.0162  0.1136 -0.0442  0.1087


α_pvalue
          Low       2       3       4    High
Small  0.0875  0.4447  0.4245  0.0070  0.0053
2      0.1549  0.2408  0.0723  0.0103  0.0140
3      0.2230  0.0299  0.0312  0.0063  0.0711
4      0.9743  0.3195  0.0320  0.0175  0.3456
Big    0.9430  0.7184  0.0767  0.6189  0.4379


β
          Low       2       3       4    High
Small  1.6307  1.4323  1.4230  1.2650  1.3763
2      1.3100  1.2602  1.2244  1.2302  1.3954
3      1.2845  1.1314  1.1418  1.1902  1.3621
4      1.0858  1.1040  1.1123  1.1646  1.4108
Big    0.9512  0.9394  0.9598  1.1013  1.2665


β_pvalue
       Low    2    3    4  High
Small  0.0  0.0  0.0  0.0   0.0
2      0.0  0.0  0.0  0.0   0.0
3      0.0  0.0  0.0  0.0   0.0
4      0.0  0.0  0.0  0.0   0.0
Big    0.0  0.0  0.0  0.0   0.0


α_se
          Low       2       3       4    High
Small  0.2534  0.1845  0.1576  0.1458  0.1760
2      0.1281  0.1074  0.1006  0.1099  0.1406
3      0.0971  0.0723  0.0747  0.0932  0.1281
4      0.0674  0.0555  0.0696  0.0865  0.1299
Big    0.0462  0.0450  0.0641  0.0888  0.1400


β_se
          Low       2       3       4    High
Small  0.0487  0.0354  0.0303  0.0280  0.0338
2      0.0246  0.0206  0.0193  0.0211  0.0270
3      0.0187  0.0139  0.0143  0.0179  0.0246
4      0.0129  0.0107  0.0134  0.0166  0.0250
Big    0.0089  0.0087  0.0123  0.0171  0.0269


λ
0.7435845588235294
λ_se
0.1562776422332414

In [66]:
'''test FF3F & Report standard errors'''
df_timeseries_est = pd.DataFrame(index=df25.columns[:-4], columns=['α','α_pvalue','β','β_pvalue','s','s_pvalue','h','h_pvalue','α_se','β_se','s_se','h_se'], dtype=float)
for i in df25.columns[:-4]:
  lm = pg.linear_regression(df25[['Mkt-RF','SMB','HML']],df25[i]-df25['RF'])
  df_timeseries_est['α'][i] = lm.coef[0]
  df_timeseries_est['α_pvalue'][i] = lm.pval[0]
  df_timeseries_est['β'][i] = lm.coef[1]
  df_timeseries_est['β_pvalue'][i] = lm.pval[1]
  df_timeseries_est['s'][i] = lm.coef[2]
  df_timeseries_est['s_pvalue'][i] = lm.pval[2]
  df_timeseries_est['h'][i] = lm.coef[3]
  df_timeseries_est['h_pvalue'][i] = lm.pval[3]
  df_timeseries_est['α_se'][i] = lm.se[0]
  df_timeseries_est['β_se'][i] = lm.se[1]
  df_timeseries_est['s_se'][i] = lm.se[2]
  df_timeseries_est['h_se'][i] = lm.se[3]

for i in df_timeseries_est.columns:
  print(i)
  print(present_in_5square(df_timeseries_est[i].round(4)))
  print('\n')

print('λ for market')
print(df25['Mkt-RF'].mean())
print('λ_se')
print(df25['Mkt-RF'].std()/(len(df25.index)**0.5))
print('\n')

print('λ for size')
print(df25['SMB'].mean())
print('λ_se')
print(df25['SMB'].std()/(len(df25.index)**0.5))
print('\n')

print('λ for value')
print(df25['HML'].mean())
print('λ_se')
print(df25['HML'].std()/(len(df25.index)**0.5))
print('\n')

α
          Low       2       3       4    High
Small -0.6725 -0.3287 -0.1314  0.1235  0.1210
2     -0.2129  0.0055  0.0075  0.0495  0.0175
3     -0.1210  0.1006  0.0313  0.0549 -0.0625
4      0.0725  0.0052  0.0339  0.0284 -0.1760
Big    0.0903 -0.0069  0.0425 -0.2145 -0.1560


α_pvalue
          Low       2       3       4    High
Small  0.0012  0.0047  0.1554  0.0441  0.1088
2      0.0028  0.9211  0.8876  0.3089  0.7551
3      0.0416  0.0530  0.5450  0.3170  0.3605
4      0.1378  0.9186  0.5430  0.6286  0.0175
Big    0.0077  0.8684  0.4063  0.0001  0.0949


β
          Low       2       3       4    High
Small  1.2495  1.0753  1.0843  0.9144  0.9595
2      1.1010  1.0317  0.9980  0.9725  1.0699
3      1.1468  1.0099  1.0011  1.0073  1.1084
4      1.0662  1.0427  1.0168  1.0337  1.1993
Big    1.0228  0.9765  0.9614  1.0426  1.1574


β_pvalue
       Low    2    3    4  High
Small  0.0  0.0  0.0  0.0   0.0
2      0.0  0.0  0.0  0.0   0.0
3      0.0  0.0  0.0  0.0   0.0
4      0.0  0.0  0.0  0.0   0.0
Big    0.0  0.0  0.0  0.0   0.0


s
          Low       2       3       4    High
Small  1.5229  1.5397  1.2127  1.2420  1.3235
2      1.1484  0.9844  0.8063  0.8062  0.9121
3      0.8120  0.5470  0.4323  0.4636  0.5923
4      0.3359  0.2084  0.2073  0.2255  0.3272
Big   -0.1550 -0.1916 -0.2316 -0.1820 -0.1767


s_pvalue
       Low    2    3    4  High
Small  0.0  0.0  0.0  0.0   0.0
2      0.0  0.0  0.0  0.0   0.0
3      0.0  0.0  0.0  0.0   0.0
4      0.0  0.0  0.0  0.0   0.0
Big    0.0  0.0  0.0  0.0   0.0


h
          Low       2       3       4    High
Small  0.3830  0.1983  0.5392  0.5774  0.9038
2     -0.2347  0.1285  0.3668  0.5755  0.8781
3     -0.2329  0.0348  0.3254  0.5629  0.8522
4     -0.3459  0.1133  0.3428  0.5537  0.9472
Big   -0.2581  0.0244  0.3178  0.6500  0.9785


h_pvalue
       Low       2    3    4  High
Small  0.0  0.0000  0.0  0.0   0.0
2      0.0  0.0000  0.0  0.0   0.0
3      0.0  0.0185  0.0  0.0   0.0
4      0.0  0.0000  0.0  0.0   0.0
Big    0.0  0.0394  0.0  0.0   0.0


α_se
          Low       2       3       4    High
Small  0.2069  0.1161  0.0924  0.0613  0.0754
2      0.0710  0.0556  0.0532  0.0486  0.0560
3      0.0593  0.0519  0.0517  0.0548  0.0684
4      0.0488  0.0507  0.0557  0.0588  0.0740
Big    0.0338  0.0416  0.0511  0.0544  0.0933


β_se
          Low       2       3       4    High
Small  0.0429  0.0241  0.0192  0.0127  0.0156
2      0.0147  0.0115  0.0110  0.0101  0.0116
3      0.0123  0.0108  0.0107  0.0114  0.0142
4      0.0101  0.0105  0.0115  0.0122  0.0153
Big    0.0070  0.0086  0.0106  0.0113  0.0194


s_se
          Low       2       3       4    High
Small  0.0684  0.0384  0.0305  0.0203  0.0249
2      0.0235  0.0184  0.0176  0.0161  0.0185
3      0.0196  0.0172  0.0171  0.0181  0.0226
4      0.0161  0.0167  0.0184  0.0194  0.0244
Big    0.0112  0.0138  0.0169  0.0180  0.0308


h_se
          Low       2       3       4    High
Small  0.0587  0.0329  0.0262  0.0174  0.0214
2      0.0202  0.0158  0.0151  0.0138  0.0159
3      0.0168  0.0147  0.0147  0.0156  0.0194
4      0.0138  0.0144  0.0158  0.0167  0.0210
Big    0.0096  0.0118  0.0145  0.0154  0.0265


λ for market
0.7435845588235294
λ_se
0.1562776422332414


λ for size
0.24319852941176473
λ_se
0.09654170500481328


λ for value
0.3972518382352941
λ_se
0.1081487804669064

In [22]:
lm = pg.linear_regression(df25[['Mkt-RF','SMB','HML']],df25['1']-df25['RF'])
lm

,names,coef,se,T,pval,r2,adj_r2,CI[2.5%],CI[97.5%]
0,Intercept,-0.672484,0.206927,-3.249858,1.190123e-03,0.675027,0.674128,-1.078508,-0.266461
1,Mkt-RF,1.249548,0.042933,29.104825,4.401046e-138,0.675027,0.674128,1.165308,1.333789
2,SMB,1.522930,0.068396,22.266390,9.545611e-91,0.675027,0.674128,1.388726,1.657133
3,HML,0.383037,0.058719,6.523218,1.053675e-10,0.675027,0.674128,0.267821,0.498253

In [70]:
df_beta = []
for i in df25.columns[:-4]:
  lm = pg.linear_regression(df25['Mkt-RF'],df25[i]-df25['RF'])
  df_beta.append(lm.coef[1])

df_alpha = []
for i in df25.columns[:-4]:
  lm = pg.linear_regression(df25['Mkt-RF'],df25[i]-df25['RF'])
  df_alpha.append(lm.coef[0])

In [78]:
'''Cross sectional test with a constant'''
lm = pg.linear_regression(df_beta,df25_mean)
lm['names'] = ['λ0^','λ^']
lm

,names,coef,se,T,pval,r2,adj_r2,CI[2.5%],CI[97.5%]
0,λ0^,0.545508,0.301212,1.811041,0.083217,0.210701,0.176384,-0.077597,1.168613
1,λ^,0.601386,0.242704,2.477860,0.020993,0.210701,0.176384,0.099315,1.103457

In [105]:
alpha = []
for i in range(25):
  alpha.append(df25_mean[i] - df_beta[i]*lm.coef[1] - lm.coef[0])

'''mean square'''
mean_square = 0
for i in alpha:
  mean_square += (i-sum(alpha)/len(alpha))**2
print('mean square')
print(mean_square/len(alpha))
print('\n')

'''average absolute'''
average_absolute = 0
for i in alpha:
  if i-(sum(alpha)/len(alpha)) >= 0:
    average_absolute += i-(sum(alpha)/len(alpha))
  else:
    average_absolute += (sum(alpha)/len(alpha)) - i
print('average absolute')
print(average_absolute/len(alpha))

mean square
0.03664464290026904


average absolute
0.14910596188336422

## Part II (Coco & Faye)